name: sanitize
on:
  push:
    branches: '**'
  pull_request:
    branches:
      - 'main'

jobs:
  unit-test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          curl https://sh.rustup.rs -sSf > installer.sh
          sh installer.sh -y
          cargo install stylua

          sudo apt-get install luarocks
          sudo luarocks install luacheck

      - name: Run formatters and linters
        run: |
          make lint
          make format args=--check
